# Generated by Django 4.1.7 on 2023-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
