# Generated by Django 4.1.7 on 2023-03-10 14:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fa-solid fa-mountain-city', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1024, 768], upload_to='services/photo'),
        ),
    ]
