# Generated by Django 4.1.7 on 2023-03-10 13:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='/img/about.jpg', force_format=None, keep_meta=True, quality=0, size=[750, 500], upload_to='car/photos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
