# Generated by Django 4.1.7 on 2023-03-10 14:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[750, 500], upload_to='car/photos/%Y/%m/'),
        ),
    ]
